def fix_timeframe_alignment():
    file_path = 'backend/utils/timeframe_alignment.py'
    
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Fix try-except blocks indentation
    content = content.replace('    async def analyze_timeframes(self, symbol: str) -> List[TimeframeSignal]:\n        """\n        Analyze multiple timeframes for a symbol\n        """\n        try:\n            signals = []\n            for timeframe in self.timeframes:\n                data = await self.get_historical_data(symbol, timeframe.value)\n                indicators = self.calculate_indicators(data, timeframe)\n                signal = self.generate_signal(indicators)\n                confidence = self.calculate_signal_confidence(indicators)\n                signals.append(TimeframeSignal(\n                    timeframe=timeframe,\n                    signal=signal,\n                    confidence=confidence\n                ))\n        except Exception as e:\n            raise HTTPException(\n                status_code=500,\n                detail=f"Error analyzing timeframes: {str(e)}"\n            )',
                           '    async def analyze_timeframes(self, symbol: str) -> List[TimeframeSignal]:\n        """\n        Analyze multiple timeframes for a symbol\n        """\n        try:\n            signals = []\n            for timeframe in self.timeframes:\n                data = await self.get_historical_data(symbol, timeframe.value)\n                indicators = self.calculate_indicators(data, timeframe)\n                signal = self.generate_signal(indicators)\n                confidence = self.calculate_signal_confidence(indicators)\n                signals.append(TimeframeSignal(\n                    timeframe=timeframe,\n                    signal=signal,\n                    confidence=confidence\n                ))\n        except Exception as e:\n            raise HTTPException(\n                status_code=500,\n                detail=f"Error analyzing timeframes: {str(e)}"\n            )')
    
    # Fix get_timeframe_signals indentation
    content = content.replace('    async def get_timeframe_signals(self, symbol: str) -> List[TimeframeSignal]:\n        """\n        Get signals from all timeframes\n        """\n        try:\n            signals = []\n            for timeframe in self.timeframes:\n                data = await self.get_historical_data(symbol, timeframe.value)\n                indicators = self.calculate_indicators(data, timeframe)\n                signal = self.generate_signal(indicators)\n                confidence = self.calculate_signal_confidence(indicators)\n                signals.append(TimeframeSignal(\n                    timeframe=timeframe,\n                    signal=signal,\n                    confidence=confidence\n                ))\n        except Exception as e:\n            raise HTTPException(\n                status_code=500,\n                detail=f"Error getting timeframe signals: {str(e)}"\n            )',
                           '    async def get_timeframe_signals(self, symbol: str) -> List[TimeframeSignal]:\n        """\n        Get signals from all timeframes\n        """\n        try:\n            signals = []\n            for timeframe in self.timeframes:\n                data = await self.get_historical_data(symbol, timeframe.value)\n                indicators = self.calculate_indicators(data, timeframe)\n                signal = self.generate_signal(indicators)\n                confidence = self.calculate_signal_confidence(indicators)\n                signals.append(TimeframeSignal(\n                    timeframe=timeframe,\n                    signal=signal,\n                    confidence=confidence\n                ))\n        except Exception as e:\n            raise HTTPException(\n                status_code=500,\n                detail=f"Error getting timeframe signals: {str(e)}"\n            )')
    
    # Fix calculate_alignment_score indentation
    content = content.replace('    def calculate_alignment_score(self, signals: List[TimeframeSignal]) -> int:\n        """\n        Calculate how many timeframes agree on the signal\n        """\n        signal_counts = {\n            SignalType.BULLISH: 0,\n            SignalType.BEARISH: 0,\n            SignalType.NEUTRAL: 0\n        }\n        \n        for signal in signals:\n            if signal.confidence >= self.signal_threshold:\n                signal_counts[signal.signal] += 1\n        \n        return max(signal_counts.values())',
                           '    def calculate_alignment_score(self, signals: List[TimeframeSignal]) -> int:\n        """\n        Calculate how many timeframes agree on the signal\n        """\n        signal_counts = {\n            SignalType.BULLISH: 0,\n            SignalType.BEARISH: 0,\n            SignalType.NEUTRAL: 0\n        }\n        \n        for signal in signals:\n            if signal.confidence >= self.signal_threshold:\n                signal_counts[signal.signal] += 1\n        \n        return max(signal_counts.values())')
    
    # Fix get_dominant_signal indentation
    content = content.replace('    def get_dominant_signal(self, signals: List[TimeframeSignal]) -> SignalType:\n        """\n        Get the most dominant signal across timeframes\n        """\n        signal_counts = {\n            SignalType.BULLISH: 0,\n            SignalType.BEARISH: 0,\n            SignalType.NEUTRAL: 0\n        }\n        \n        for signal in signals:\n            if signal.confidence >= self.signal_threshold:\n                signal_counts[signal.signal] += 1\n        \n        return max(signal_counts.items(), key=lambda x: x[1])[0]',
                           '    def get_dominant_signal(self, signals: List[TimeframeSignal]) -> SignalType:\n        """\n        Get the most dominant signal across timeframes\n        """\n        signal_counts = {\n            SignalType.BULLISH: 0,\n            SignalType.BEARISH: 0,\n            SignalType.NEUTRAL: 0\n        }\n        \n        for signal in signals:\n            if signal.confidence >= self.signal_threshold:\n                signal_counts[signal.signal] += 1\n        \n        return max(signal_counts.items(), key=lambda x: x[1])[0]')
    
    # Fix calculate_overall_confidence indentation
    content = content.replace('    def calculate_overall_confidence(self, signals: List[TimeframeSignal]) -> float:\n        """\n        Calculate overall confidence score\n        """\n        total_confidence = 0\n        valid_signals = 0\n        \n        for signal in signals:\n            if signal.confidence >= self.signal_threshold:\n                total_confidence += signal.confidence\n                valid_signals += 1\n        \n        return total_confidence / valid_signals if valid_signals > 0 else 0.0',
                           '    def calculate_overall_confidence(self, signals: List[TimeframeSignal]) -> float:\n        """\n        Calculate overall confidence score\n        """\n        total_confidence = 0\n        valid_signals = 0\n        \n        for signal in signals:\n            if signal.confidence >= self.signal_threshold:\n                total_confidence += signal.confidence\n                valid_signals += 1\n        \n        return total_confidence / valid_signals if valid_signals > 0 else 0.0')
    
    # Fix get_historical_data indentation
    content = content.replace('    async def get_historical_data(self, symbol: str, timeframe: str) -> pd.DataFrame:\n        """\n        Get historical price data\n        """\n        # Implementation depends on data source\n        return pd.DataFrame()',
                           '    async def get_historical_data(self, symbol: str, timeframe: str) -> pd.DataFrame:\n        """\n        Get historical price data\n        """\n        # Implementation depends on data source\n        return pd.DataFrame()')
    
    with open(file_path, 'w') as f:
        f.write(content)

if __name__ == "__main__":
    fix_timeframe_alignment()
